// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  homepage?: unknown;
  layout?: unknown;
  seo?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface PracticeArea {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  url: string;
  icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  icon_width?: number;
  icon_height?: number;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    practice_areas: PracticeArea;
  }
}